import java.uti.Scanner;

public class ConnectFour {
  
  public static void main(String[] args) {
    
    Scanner in = new Scanner(Scanner.in)
      
    char[][] grid = new char[6][7];
    
    // Initializing array
    for (int row = 0; row < grid.length; row++) {
      for (int col = 0; col < grid[0].length; col++) {
        grid[row][col] = ' ';
      }
    }
    
    int turn = 1;
    char player = 'R';
    boolean winner = false;
    
    // First turn of game
    while(winner == false && turn <= 42) {
      boolean v
    }
  
  
  }
}
